### ISSUE TITLE
StartShadowsocks无法使用

### ISSUE THREAD

**Issue by FatChou** [eycorsican/go-tun2socks-ios#4]
开启pac，调用StartShadowsocks传入地址，端口，加密方式（AES-256-CFB），密码，无法使用，也没有日志。

**Comment by eycorsican** [comment]
跟 pac 没什么关系，你对 iOS 的 PacketTunnel 有根本性的误解，建议去了解下一些实现完整的 app 的用法，比如 NEKit

**Comment by ameue** [comment]
启动后用Tun2socksInputPacket、writePacket读、写packet flow没有用
